import { NextResponse } from "next/server";
import { presentationHistory } from "@/lib/serverStore";

export async function GET(request, { params }) {
  const presId = params?.id ? Number(params.id) || params.id : "1";
  const item = presentationHistory.find((p) => p.id === presId || String(p.id) === String(presId)) || presentationHistory[0];

  const wpm = item?.wpm || 142;
  const fillerCount = item?.fillerWords ?? 2;
  const fillerList = item?.fillerBreakdown || "um: 1, like: 1";
  const confidence = item?.confidence || 86;
  const clarity = item?.clarity || 88;
  const engagement = item?.engagement || 85;
  const transcriptSnippet = (item?.transcript || "Clear presentation speech run.").replace(/[\r\n]/g, " ").slice(0, 200);

  const reportBody = `LOGOS.AI OFFICIAL VOCAL & PRESENTATION ANALYSIS REPORT
================================================================================
Presentation Run ID: ${presId}
Date: ${item?.date || new Date().toISOString().split("T")[0]}
Duration: ${item?.duration || "30s"}
--------------------------------------------------------------------------------
VOCAL & PROSODY METRICS:
- Speaking Pace: ${wpm} WPM (${wpm >= 120 && wpm <= 165 ? "Optimal Pacing" : "Adjust Pace"})
- Filler Words Logged: ${fillerCount} (${fillerList})
- Vocal Clarity Score: ${clarity}%
- Confidence Index: ${confidence}%
- Audience Engagement: ${engagement}%
--------------------------------------------------------------------------------
TRANSCRIPT SUMMARY:
"${transcriptSnippet}"
--------------------------------------------------------------------------------
COACHING RECOMMENDATIONS:
- Keep vocal pacing in the 130-155 WPM range for optimal retention.
- Minimize verbal hesitation markers by pausing silently between clauses.
- Project vocal inflection on core theses and evidentiary citations.
================================================================================
Generated by LOGOS.AI Presentation & Speech Coaching Engine
`;

  const pdfStream = `%PDF-1.4
1 0 obj
<< /Title (LOGOS.AI Presentation Prosody Report - ${presId})
   /Author (LOGOS.AI Speech Coaching Engine)
   /Subject (Presentation Vocal Analysis) >>
endobj
2 0 obj
<< /Length ${Buffer.byteLength(reportBody, 'utf-8')} >>
stream
${reportBody}
endstream
endobj
trailer
<< /Root 1 0 R >>
%%EOF`;

  return new NextResponse(pdfStream, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="logos-ai-presentation-report-${presId}.pdf"`,
    },
  });
}
