"use client";

import { useState } from 'react';

const rows = [['Argument quality','86','30%'],['Evidence use','78','20%'],['Logical consistency','91','20%'],['Rebuttal effectiveness','82','15%'],['Communication','88','15%']];
function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], {type})); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }

export default function ReportsPage() {
  const [notice, setNotice] = useState('');
  const exportCsv = () => { download('logos-performance-report.csv', `Metric,Score,Weight\n${rows.map(r=>r.join(',')).join('\n')}\nOverall,85,100%`, 'text/csv'); setNotice('CSV report downloaded.'); };
  const exportSummary = () => { download('logos-coaching-summary.txt', 'LOGOS.AI PERFORMANCE SUMMARY\n\nOverall score: 85 / 100\nFocus next: evidence depth, rebuttal framing, and deliberate pauses.\n', 'text/plain'); setNotice('Coaching summary downloaded.'); };
  return <div className="page-shell"><div className="page-title"><div className="eyebrow">Reporting & export engine</div><h1 className="display">Make progress <span className="red">visible.</span></h1><p>Turn your debate and presentation history into clear scorecards, coaching plans, and shareable progress reports.</p></div>{notice && <div className="notice" style={{marginTop:30}}>{notice}</div>}<div className="report-grid"><div className="report-card"><div className="eyebrow">Debate & speech analysis</div><h3>Assessment scorecard</h3><p>A compact performance view with argument quality, logical reasoning, rebuttal, and vocal metrics.</p><button className="btn btn-red" onClick={() => setNotice('PDF export is ready to connect to the report service. Use CSV for this demo build.')}>Preview assessment ↗</button></div><div className="report-card"><div className="eyebrow">Weighted performance matrix</div><h3>Excel / CSV export</h3><p>Download the five-dimension scoring model that powers your overall performance score.</p><button className="btn btn-dark" onClick={exportCsv}>Export CSV ↗</button></div><div className="report-card"><div className="eyebrow">Coaching & learning progress</div><h3>Learning plan</h3><p>Your next exercises, skill gaps, and milestones — ready to share with a coach or educator.</p><button className="btn btn-ghost" onClick={exportSummary}>Download summary ↗</button></div></div><div className="panel" style={{marginTop:28}}><div className="panel-title"><h2>Latest scorecard</h2><span className="label muted">Session · AI governance</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Metric</th><th>Score</th><th>Weight</th><th>Signal</th></tr></thead><tbody>{rows.map(([metric,score,weight]) => <tr key={metric}><td>{metric}</td><td className="score-text">{score} / 100</td><td>{weight}</td><td><span className="tag">{Number(score) >= 85 ? 'Strong' : 'Focus next'}</span></td></tr>)}</tbody></table></div></div></div>;
}