"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { getCurrentUser, getDebateRequests, getHumanDebates, getLearners, updateDebateRequest, Person, DebateRequest, HumanDebate } from "@/services/auth";

export default function ExpertDashboard() {
  const [name, setName] = useState("Debate Expert");
  const [learners, setLearners] = useState<Person[]>([]);
  const [requests, setRequests] = useState<DebateRequest[]>([]);
  const [debates, setDebates] = useState<HumanDebate[]>([]);
  const [error, setError] = useState("");

  useEffect(() => { void Promise.all([getCurrentUser(), getLearners(), getDebateRequests(), getHumanDebates()]).then(([user, learnerList, requestList, debateList]) => { setName(user.full_name); setLearners(learnerList); setRequests(requestList); setDebates(debateList); }).catch((value: Error) => setError(value.message)); }, []);

  async function decide(request: DebateRequest, status: "ACCEPTED" | "REJECTED") { try { const result = await updateDebateRequest(request.id, status); setRequests((items) => items.map((item) => item.id === request.id ? { ...item, status } : item)); if (status === "ACCEPTED" && "request_id" in result) setDebates((items) => [result, ...items]); } catch (value) { setError(value instanceof Error ? value.message : "Unable to update request"); } }

  return <main className="min-h-screen bg-slate-100 p-6"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold uppercase tracking-widest text-amber-700">Debate expert dashboard</p><h1 className="mt-2 text-3xl font-semibold">Welcome, {name}</h1></header><section className="grid gap-4 sm:grid-cols-3"><Stat label="Learners" value={learners.length}/><Stat label="Pending requests" value={requests.filter((item) => item.status === "PENDING").length}/><Stat label="Active debates" value={debates.filter((item) => item.status === "ACTIVE").length}/></section><section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Learner profiles</h2><span className="text-sm text-slate-500">{learners.length} available</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{learners.length ? learners.map((learner) => <Link className="rounded-lg border border-slate-200 p-4 hover:bg-slate-50" href={`/expert/learners/${learner.id}`} key={learner.id}><p className="font-medium text-slate-900">{learner.full_name}</p><p className="mt-1 text-sm text-slate-500">{learner.email}</p></Link>) : <p className="text-sm text-slate-500">No learners available.</p>}</div></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Debate requests</h2>{error ? <p className="mt-3 text-sm text-rose-600">{error}</p> : null}<div className="mt-4 space-y-3">{requests.length ? requests.map((request) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 p-4" key={request.id}><div><p className="font-medium">{request.topic}</p><p className="text-sm text-slate-500">Learner #{request.learner_id} · {request.status}</p></div>{request.status === "PENDING" ? <div className="flex gap-2"><button onClick={() => void decide(request, "ACCEPTED")} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white">Accept</button><button onClick={() => void decide(request, "REJECTED")} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Reject</button></div> : null}</div>) : <p className="text-sm text-slate-500">No requests yet.</p>}</div></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Your live debate rooms</h2><div className="mt-4 space-y-2">{debates.length ? debates.map((debate) => <Link className="block rounded-lg border border-slate-200 p-4 hover:bg-slate-50" href={`/community/${debate.id}`} key={debate.id}><p className="font-medium">{debate.topic}</p><p className="text-sm text-slate-500">{debate.status} · Open shared chat</p></Link>) : <p className="text-sm text-slate-500">Accepted debates will appear here.</p>}</div></section></div></main>;
}

function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
