"use client";

import { useState } from 'react';

const topics = ['Autonomous AI systems should be held legally liable for unintended damages.','Universal basic income is essential in an automated economy.','Social media platforms should be regulated like public utilities.'];
const personas = { 'The Contrarian':'Presses every assumption and asks who pays the cost.', 'The Academic':'Requests definitions, evidence quality, and a defensible source.', 'The Strategist':'Tests implementation, incentives, and second-order effects.' };

export default function SimulationPage() {
  const [setup, setSetup] = useState(true);
  const [topic, setTopic] = useState(topics[0]);
  const [format, setFormat] = useState('Parliamentary Debate');
  const [position, setPosition] = useState('Affirmative');
  const [persona, setPersona] = useState('The Contrarian');
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState([]);
  const [turn, setTurn] = useState(1);
  const [saved, setSaved] = useState(false);
  const start = () => { setSetup(false); setMessages([{role:'system', text:`Session initialized · ${format} · ${position}`},{role:'ai',text:`I’ll argue the ${position === 'Affirmative' ? 'Negative' : 'Affirmative'} perspective. Present your opening case for “${topic}”.`}]); };
  const send = e => { e.preventDefault(); if (!input.trim()) return; const text=input.trim(); setInput(''); const rebuttals = [`Your claim is clear, but what evidence separates a plausible benefit from a scalable policy? ${personas[persona]}`, `You’re assuming the implementation is frictionless. Who carries the cost, and what mechanism prevents the obvious failure mode?`, `That answers the principle, not the trade-off. Give me one measurable threshold that would change your position.`]; setMessages(prev => [...prev,{role:'user',text},{role:'ai',text:rebuttals[turn % rebuttals.length]}]); setTurn(turn+1); };
  if (setup) return <div className="page-shell"><div className="page-title"><div className="eyebrow">Debate session management · milestone 01</div><h1 className="display">Practice under <span className="red">pressure.</span></h1><p>Configure a live AI opponent, choose your side, and build the reflexes that make a strong argument survive cross-examination.</p></div><div className="workspace-grid"><section className="panel"><div className="panel-title"><h2>Session parameters</h2><span className="label muted">Ready to deploy</span></div><label>Debate topic</label><select value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}<option value="Custom topic">Custom topic</option></select><label>Debate format</label><select value={format} onChange={e=>setFormat(e.target.value)}><option>One-on-One Debate</option><option>Parliamentary Debate</option><option>Oxford Debate</option><option>Policy Debate</option><option>Public Forum Debate</option></select><div className="split"><div><label>Your position</label><select value={position} onChange={e=>setPosition(e.target.value)}><option>Affirmative</option><option>Negative</option></select></div><div><label>Opponent persona</label><select value={persona} onChange={e=>setPersona(e.target.value)}>{Object.keys(personas).map(p=><option key={p}>{p}</option>)}</select></div></div><button className="btn btn-red" style={{width:'100%',marginTop:25}} onClick={start}>Initialize live simulation ↗</button></section><aside className="panel panel-dark"><div className="panel-title"><h3>Opponent profile</h3><span className="label">Agentic</span></div><h2 style={{fontSize:30}}>{persona}</h2><p className="muted" style={{color:'#a6a8a5',lineHeight:1.7}}>{personas[persona]}</p><div style={{marginTop:45}}><div className="label muted">Engine protocols</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{['Dynamic rebuttal','Fallacy audit','Coaching hints','Multi-turn memory'].map(x=><span className="tag" style={{background:'#2c3330',color:'#9cd4ac'}} key={x}>{x}</span>)}</div></div></aside></div></div>;
  return <div className="page-shell"><div className="dash-head"><div><div className="eyebrow">Live session · {format} · {position}</div><h1 className="display">Debate <span className="red">terminal.</span></h1></div><button className="btn btn-ghost" onClick={()=>setSaved(true)}>{saved ? 'Session saved ✓' : 'Save & complete'}</button></div><div className="workspace-grid"><section className="terminal"><div className="terminal-head"><span className="dots"><i/><i/><i/></span><span>LOGOS.AI / {topic.toUpperCase()}</span><span>TURN {turn}</span></div><div className="terminal-log">{messages.map((m,i)=><div className="message" key={i}><div className={`message-meta ${m.role === 'user' ? 'message-user' : m.role === 'ai' ? 'message-ai' : 'message-system'}`}>{m.role === 'user' ? 'YOU' : m.role === 'ai' ? `AI OPPONENT · ${persona.toUpperCase()}` : 'SYSTEM'}</div><div className="message-text">{m.text}</div></div>)}</div><form className="chat-form" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Type your argument or rebuttal..." /><button className="btn btn-red" type="submit">Transmit ↗</button></form></section><aside style={{display:'flex',flexDirection:'column',gap:16}}><div className="panel"><div className="label muted">Opponent pressure</div><strong style={{display:'block',fontSize:42,color:'var(--red)',margin:'14px 0'}}>96.5%</strong><span className="muted">High-pressure cross-examination</span></div><div className="panel"><div className="panel-title"><h3>Logic audit</h3><span className="label muted">Turn {turn}</span></div><div className="notice">✓ No fallacy flagged in the last turn.</div><p className="muted" style={{fontSize:13,lineHeight:1.6}}>Keep one piece of evidence attached to every major claim.</p></div><div className="panel panel-dark" style={{flex:1}}><div className="eyebrow">Coaching assistant</div><p style={{lineHeight:1.7}}>Answer the opponent’s strongest point first. Then return to the mechanism that makes your proposal work.</p></div></aside></div></div>;
}