"""increase_debate_position_length

Revision ID: 64e73a15851c
Revises: 4f236726ea1a
Create Date: 2026-09-02 08:31:49.107803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e73a15851c'
down_revision = '4f236726ea1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
