import { NextResponse } from "next/server";
import { debateHistory, sessions } from "@/lib/serverStore";

export async function GET(request, { params }) {
  const sessionId = params?.id ? Number(params.id) || params.id : "1";
  
  const debate = debateHistory.find((d) => d.id === sessionId || String(d.id) === String(sessionId))
    || sessions.find((s) => s.id === sessionId || String(s.id) === String(sessionId))
    || debateHistory[0];

  const topic = debate?.topic || "Autonomous AI Systems Liability";
  const format = debate?.format || "Parliamentary Debate";
  const position = debate?.position || debate?.assigned_position || "Affirmative";
  const persona = debate?.opponent_persona || "The Contrarian";
  const overall = debate?.scores?.overall || debate?.score || 86;
  const consistency = debate?.scores?.consistency || 88;
  const argQuality = debate?.scores?.argQuality || 87;
  const evidence = debate?.scores?.evidence || 82;
  const rebuttal = debate?.scores?.rebuttal || 84;
  const verdict = debate?.verdict || `${position} Ballot Awarded`;
  const review = debate?.coaching_review || "Substantiate core claims with verified empirical citations.";
  
  const fallaciesCount = Array.isArray(debate?.fallacies) ? debate.fallacies.length : 0;
  const fallacyTypes = Array.isArray(debate?.fallacies) && debate.fallacies.length > 0
    ? debate.fallacies.map((f) => f.fallacy_type || f).join(", ")
    : "None recorded";

  const safeTopic = topic.replace(/[\r\n]/g, " ").slice(0, 80);
  const safeReview = review.replace(/[\r\n]/g, " ").slice(0, 300);

  const reportBody = `LOGOS.AI OFFICIAL DEBATE & RHETORIC ASSESSMENT REPORT
================================================================================
Debate Session ID: ${sessionId}
Date Generated: ${new Date().toISOString().split("T")[0]}
Motion / Topic: ${safeTopic}
Format: ${format} | Debater Position: ${position} | AI Opponent: ${persona}
--------------------------------------------------------------------------------
ADJUDICATION VERDICT: ${verdict}
Overall Rhetoric Score: ${overall} / 100
- Argument Construction: ${argQuality}%
- Logical Consistency: ${consistency}%
- Evidence & Solvency: ${evidence}%
- Rebuttal Pressure: ${rebuttal}%
- Total Fallacies Flagged: ${fallaciesCount} (${fallacyTypes})
--------------------------------------------------------------------------------
COACHING ASSISTANT TACTICAL REVIEW:
${safeReview}
================================================================================
Generated by LOGOS.AI Agentic Debate & Presentation Coaching Platform
`;

  const pdfStream = `%PDF-1.4
1 0 obj
<< /Title (LOGOS.AI Debate Assessment Report - ${safeTopic})
   /Author (LOGOS.AI Agentic Debate Coach)
   /Subject (Debate Adjudication and Coaching Report) >>
endobj
2 0 obj
<< /Length ${Buffer.byteLength(reportBody, 'utf-8')} >>
stream
${reportBody}
endstream
endobj
trailer
<< /Root 1 0 R >>
%%EOF`;

  return new NextResponse(pdfStream, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="logos-ai-debate-report-session-${sessionId}.pdf"`,
    },
  });
}
