"""
main.py
-------
End-to-end orchestrator for the debate coaching pipeline:

  USER (topic + argument)
      -> Counterargument Generation (claims, analysis, counterarguments)
      -> AI Debate Simulation (multi-turn, context-maintained)
      -> Performance Evaluation (logic/clarity/evidence/rebuttal)
      -> Coaching Recommendation (weaknesses + feedback)
      -> Personalized Learning Plan (goals + activities)
      -> Performance Dashboard (JSON payload for the frontend)

This file is the AI/ML "glue" — it doesn't render UI, it just produces
the structured data your dashboard front-end would consume.
"""

import json

from llm_client import LLMClient
from counterargument import run_counterargument_stage
from debate_simulation import DebateSimulator
from evaluation import evaluate_performance
from coaching import run_coaching_stage


def run_pipeline(topic: str, user_argument: str, opponent_stance: str,
                  user_turns: list[str], difficulty: str = "intermediate") -> dict:
    """
    user_turns: the sequence of things the user says during the live debate
                (in a real app these come in one at a time from the UI;
                here we accept a pre-recorded list for demonstration /
                batch evaluation purposes).
    """
    llm = LLMClient()

    # 1. Counterargument Generation
    stage1 = run_counterargument_stage(llm, topic, user_argument)

    # 2. AI Debate Simulation (multi-turn, context maintained via DebateSimulator)
    simulator = DebateSimulator(llm, topic, opponent_stance, difficulty)
    simulator.opening_statement()
    for turn in user_turns:
        simulator.respond(turn)
    transcript = simulator.get_transcript()

    # 3. Performance Evaluation
    evaluation = evaluate_performance(llm, topic, transcript)

    # 4 & 5. Coaching Recommendation + Personalized Learning Plan
    stage4_5 = run_coaching_stage(llm, evaluation)

    # Final Performance Dashboard payload
    dashboard = {
        "topic": topic,
        "counterargument_analysis": stage1,
        "debate_transcript": transcript,
        "evaluation": evaluation,
        "coaching": stage4_5["coaching"],
        "learning_plan": stage4_5["learning_plan"],
    }
    return dashboard


if __name__ == "__main__":
    # Example run — replace with real user input / UI wiring
    result = run_pipeline(
        topic="Should social media platforms be legally liable for user-posted misinformation?",
        user_argument=(
            "Platforms should be held liable because they profit from engagement "
            "generated by misinformation and have the technical means to detect it."
        ),
        opponent_stance="Platforms should NOT be held liable",
        user_turns=[
            "Platforms already use algorithms to detect other harmful content, "
            "so detecting misinformation is technically feasible too.",
            "Holding them liable creates a financial incentive to actually invest "
            "in moderation instead of treating it as an afterthought.",
        ],
        difficulty="intermediate",
    )
    print(json.dumps(result, indent=2))
    