"use client";

import Link from 'next/link';

const skills = [['Logical consistency',88],['Argument construction',84],['Vocal clarity & cadence',80],['Filler word control',92],['Rebuttal effectiveness',78]];
const sessions = [['AI legal liability & regulation','Oxford Debate','86.4%','Completed'],['Universal basic income feasibility','Parliamentary','81.2%','Completed'],['Space colonization funding','AI Simulation','79.5%','Completed']];

export default function DashboardPage() {
  return <div className="page-shell"><div className="dash-head"><div><div className="eyebrow">Learner dashboard · profile matrix active</div><h1 className="display">Welcome, <span className="red">Brijnandan.</span></h1><p className="muted">Your rhetoric has improved 12% across the last five sessions.</p></div><Link className="btn btn-red" href="/simulation">New practice ↗</Link></div><div className="stat-grid"><div className="stat"><span className="label muted">Debates completed</span><strong>14</strong><span className="muted">+3 this month</span></div><div className="stat"><span className="label muted">Average score</span><strong className="red-text">88.5%</strong><span className="muted">+4.2% vs last month</span></div><div className="stat"><span className="label muted">Active drill</span><strong>Level 02</strong><span className="muted">Filler control</span></div><div className="stat"><span className="label muted">Top avoided fallacy</span><strong style={{fontSize:22}}>Straw man</strong><span className="muted">Keep the streak</span></div></div><div className="dash-grid"><section className="panel"><div className="panel-title"><h2>Rhetorical skill matrix</h2><span className="label muted">Current profile</span></div>{skills.map(([label,value])=><div className="skill-row" key={label}><div className="skill-label"><span>{label}</span><b className="red">{value}%</b></div><div className="skill-track"><i style={{width:`${value}%`}}/></div>)}<Link href="/analyze" className="btn btn-ghost" style={{marginTop:15}}>Run argument audit ↗</Link></section><aside><div className="panel panel-dark"><div className="eyebrow">Coaching engine</div><h2 style={{fontSize:24,margin:'15px 0'}}>Level 02 · Competent debater</h2><p style={{color:'#a6a8a5',lineHeight:1.7}}>Your logic is reliable. The next lift comes from deeper evidence and cleaner rebuttal framing.</p><div className="label" style={{color:'#8bd9e7',marginTop:25}}>Active learning step</div><p>Evidence-backed counterpoints</p></div><div className="panel" style={{marginTop:16}}><div className="panel-title"><h3>Recommended drills</h3><span className="label muted">3 queued</span></div>{['Defend a claim with two sources','Spot the hidden premise','90-second no-filler opening'].map((x,i)=><div className="finding" key={x}><b>0{i+1}</b><p>{x}</p></div>)}</div></aside></div><div className="panel" style={{marginTop:24}}><div className="panel-title"><h2>Recent debate sessions</h2><Link className="label" href="/reports" style={{color:'var(--red)'}}>View reports ↗</Link></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Topic</th><th>Format</th><th>Score</th><th>Status</th></tr></thead><tbody>{sessions.map(([topic,format,score,status])=><tr key={topic}><td>{topic}</td><td>{format}</td><td className="score-text">{score}</td><td><span className="tag">{status}</span></td></tr>)}</tbody></table></div></div></div>;
}